In [1]:
%pip install xgboost


[notice] A new release of pip is available: 24.1.1 -> 24.2
[notice] To update, run: pip3.12 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [2]:
import xgboost as xgb
print("XGBoost imported successfully!")

XGBoost imported successfully!


In [4]:
import sys
print(sys.executable)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import xgboost as xgb
import warnings

# Suppress specific warnings from xgboost
warnings.filterwarnings(action='ignore', category=UserWarning, message='.*gpu_id.*')
warnings.filterwarnings(action='ignore', category=UserWarning, message='.*gpu_hist.*')

# Load data
file_path = r"/home/innobridge/sherry/Final_Balanced_Data.csv"
data = pd.read_csv(file_path)

# Define poverty threshold and create target variable
poverty_threshold = 13590
data['poverty_status'] = np.where(data['PINCP'] <= poverty_threshold, 1, 0)

# Drop the PINCP column
data = data.drop(columns=['PINCP'])

data_sampled = data.sample(n=10000, random_state=42)

# Split data into features and target
X = data.drop(columns=['poverty_status'])
Y = data['poverty_status']

# Split data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=18)

# Define parameter grid for GridSearchCV
param_grid = {
    'n_estimators': [700, 800],             # Number of boosted trees to fit
    'max_depth': [15, 20],                  # Maximum depth of a tree
    'learning_rate': [0.01, 0.03],          # Step size shrinkage
    'subsample': [0.6, 0.8, 1],             # Subsample ratio of the training instance
    'colsample_bytree': [0.5, 0.6],         # Subsample ratio of columns when constructing each tree
    'colsample_bylevel': [0.6, 0.8, 1],     # Subsample ratio of columns for each split, in each level
    'colsample_bynode': [0.6, 0.8, 1],      # Subsample ratio of columns for each split, in each node
    'min_child_weight': [3, 5],             # Minimum sum of instance weight (hessian) needed in a child
    'gamma': [0.1],                         # Minimum loss reduction required to make a further partition on a leaf node of the tree
    'reg_alpha': [0, 0.1, 1, 10],           # L1 regularization term on weights
    'reg_lambda': [1, 1.5, 2, 5],           # L2 regularization term on weights
    'scale_pos_weight': [1, 3, 5],          # Balancing of positive and negative weights
    'tree_method': ['hist'],                # Use histogram-based method for training
    'device': ['cuda']                      # Specify the GPU device
}

# Initialize XGBoost classifier without use_label_encoder, using GPU
xgb_model = xgb.XGBClassifier(random_state=18, eval_metric='logloss')

# Perform grid search
grid_search = GridSearchCV(estimator=xgb_model, param_grid=param_grid, scoring='accuracy', cv=3, verbose=1, n_jobs=-1)
grid_search.fit(X_train, Y_train)

# Get the best model
best_xgb_model = grid_search.best_estimator_
print("Best parameters found: ", grid_search.best_params_)

# Make predictions with the best model
predictions = best_xgb_model.predict(X_test)

# Calculate evaluation metrics
accuracy = accuracy_score(Y_test, predictions)
precision = precision_score(Y_test, predictions)
recall = recall_score(Y_test, predictions)
f1 = f1_score(Y_test, predictions)
conf_matrix = confusion_matrix(Y_test, predictions)

# Print evaluation metrics
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")
print(f"Confusion Matrix: \n{conf_matrix}")

/home/innobridge/anaconda3/bin/python
Fitting 3 folds for each of 41472 candidates, totalling 124416 fits


KeyboardInterrupt: 

In [24]:
import sys
print(sys.executable)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import xgboost as xgb
import warnings

# Suppress specific warnings from xgboost
warnings.filterwarnings(action='ignore', category=UserWarning, message='.*gpu_id.*')
warnings.filterwarnings(action='ignore', category=UserWarning, message='.*gpu_hist.*')

# Load data
file_path = r"/home/innobridge/sherry/Final_Balanced_Data.csv"
data = pd.read_csv(file_path)

# Define poverty threshold and create target variable
poverty_threshold = 13590
data['poverty_status'] = np.where(data['PINCP'] <= poverty_threshold, 1, 0)

# Drop the PINCP column
data = data.drop(columns=['PINCP'])

data_sampled = data.sample(n=10000, random_state=42)

# Split data into features and target
X = data.drop(columns=['poverty_status'])
Y = data['poverty_status']

# Split data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=18)

# Define parameter grid for GridSearchCV
param_grid = {
    'learning_rate': [0.01, 0.03],          # Step size shrinkage
    'subsample': [0.6, 0.8, 1],             # Subsample ratio of the training instance
    'colsample_bytree': [0.5, 0.6],         # Subsample ratio of columns when constructing each tree
    'colsample_bylevel': [0.6, 0.8, 1],     # Subsample ratio of columns for each split, in each level
    'colsample_bynode': [0.6, 0.8, 1],      # Subsample ratio of columns for each split, in each node
    'min_child_weight': [3, 5],             # Minimum sum of instance weight (hessian) needed in a child
    'gamma': [0.1],                         # Minimum loss reduction required to make a further partition on a leaf node of the tree
    'reg_alpha': [0, 0.1, 1, 10],           # L1 regularization term on weights
    'reg_lambda': [1, 1.5, 2, 5],           # L2 regularization term on weights
    'scale_pos_weight': [1, 3, 5],          # Balancing of positive and negative weights
    'tree_method': ['hist'],                # Use histogram-based method for training
    'device': ['cuda']                      # Specify the GPU device
}

# Initialize XGBoost classifier without use_label_encoder, using GPU
xgb_model = xgb.XGBClassifier(random_state=18, eval_metric='logloss')

# Perform grid search
grid_search = GridSearchCV(estimator=xgb_model, param_grid=param_grid, scoring='accuracy', cv=3, verbose=1, n_jobs=-1)
grid_search.fit(X_train, Y_train)

# Get the best model
best_xgb_model = grid_search.best_estimator_
print("Best parameters found: ", grid_search.best_params_)

# Make predictions with the best model
predictions = best_xgb_model.predict(X_test)

# Calculate evaluation metrics
accuracy = accuracy_score(Y_test, predictions)
precision = precision_score(Y_test, predictions)
recall = recall_score(Y_test, predictions)
f1 = f1_score(Y_test, predictions)
conf_matrix = confusion_matrix(Y_test, predictions)

# Print evaluation metrics
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")
print(f"Confusion Matrix: \n{conf_matrix}")

/home/innobridge/anaconda3/bin/python
Fitting 3 folds for each of 10368 candidates, totalling 31104 fits


KeyboardInterrupt: 

In [57]:
import sys
print(sys.executable)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import xgboost as xgb
import warnings

# Suppress specific warnings from xgboost
warnings.filterwarnings(action='ignore', category=UserWarning, message='.*gpu_id.*')
warnings.filterwarnings(action='ignore', category=UserWarning, message='.*gpu_hist.*')

# Load data
file_path = r"/home/innobridge/sherry/Final_Balanced_Data.csv"
data = pd.read_csv(file_path)

# Define poverty threshold and create target variable
poverty_threshold = 13590
data['poverty_status'] = np.where(data['PINCP'] <= poverty_threshold, 1, 0)

# Drop the PINCP column
data = data.drop(columns=['PINCP'])

# Split data into features and target
X = data.drop(columns=['poverty_status'])
Y = data['poverty_status']

# Split data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=18)

# Define parameter grid for GridSearchCV
param_grid = {
    'n_estimators': [182],             
    'max_depth': [6], 
    'learning_rate': [0.2],          
    'subsample': [0.75],             
    'tree_method': ['hist'],  # Use GPU for training
    'device': ['cuda'],  # Set device to CUDA for GPU training
    'colsample_bytree': [0.8],        
    'colsample_bylevel': [1],
    'colsample_bynode': [1],      
    'min_child_weight': [3],  
    'gamma': [0.2],  # Minimum loss reduction required to make a further partition on a leaf node of the tree
    'reg_alpha': [10],  # L1 regularization term on weights
    'reg_lambda': [5, 6, 7],  # L2 regularization term on weights
    'scale_pos_weight': [0.5, 1],
}

# Initialize XGBoost classifier without use_label_encoder, using GPU
xgb_model = xgb.XGBClassifier(random_state=18, eval_metric='logloss')

# Perform grid search
grid_search = GridSearchCV(estimator=xgb_model, param_grid=param_grid, scoring='accuracy', cv=3, verbose=1, n_jobs=-1)
grid_search.fit(X_train, Y_train)

# Get the best model
best_xgb_model = grid_search.best_estimator_
print("Best parameters found: ", grid_search.best_params_)

# Make predictions with the best model
predictions = best_xgb_model.predict(X_test)

# Calculate evaluation metrics
accuracy = accuracy_score(Y_test, predictions)
precision = precision_score(Y_test, predictions)
recall = recall_score(Y_test, predictions)
f1 = f1_score(Y_test, predictions)
conf_matrix = confusion_matrix(Y_test, predictions)

# Print evaluation metrics
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")
print(f"Confusion Matrix: \n{conf_matrix}")

/home/innobridge/anaconda3/bin/python
Fitting 3 folds for each of 6 candidates, totalling 18 fits
Best parameters found:  {'colsample_bylevel': 1, 'colsample_bynode': 1, 'colsample_bytree': 0.8, 'device': 'cuda', 'gamma': 0.2, 'learning_rate': 0.2, 'max_depth': 6, 'min_child_weight': 3, 'n_estimators': 182, 'reg_alpha': 10, 'reg_lambda': 5, 'scale_pos_weight': 1, 'subsample': 0.75, 'tree_method': 'hist'}
Accuracy: 0.8145347023966605
Precision: 0.8308713608837763
Recall: 0.7886768401938502
F1 Score: 0.8092244479952619
Confusion Matrix: 
[[70225 13350]
 [17573 65584]]


In [58]:
import sys
print(sys.executable)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import xgboost as xgb
import warnings

# Suppress specific warnings from xgboost
warnings.filterwarnings(action='ignore', category=UserWarning, message='.*gpu_id.*')
warnings.filterwarnings(action='ignore', category=UserWarning, message='.*gpu_hist.*')

# Load data
file_path = r"/home/innobridge/sherry/Final_Balanced_Data.csv"
data = pd.read_csv(file_path)

# Define poverty threshold and create target variable
poverty_threshold = 13590
data['poverty_status'] = np.where(data['PINCP'] <= poverty_threshold, 1, 0)

# Drop the PINCP column
data = data.drop(columns=['PINCP'])

# Split data into features and target
X = data.drop(columns=['poverty_status'])
Y = data['poverty_status']

# Split data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=18)

# Define parameter grid for GridSearchCV
param_grid = {
    'n_estimators': [182],             
    'max_depth': [6],   
    'learning_rate': [0.2], 
    'subsample': [0.75],
    'colsample_bylevel': [1], 
    'colsample_bytree': [0.8],
    'colsample_bynode': [1],      
    'min_child_weight': [3],
     'gamma': [0.2],                        
    'reg_alpha': [10], 
     'reg_lambda': [5],  
    'scale_pos_weight': [1],
}

# Initialize XGBoost classifier without use_label_encoder, using GPU
xgb_model = xgb.XGBClassifier(random_state=18, eval_metric='logloss')

# Perform grid search
grid_search = GridSearchCV(estimator=xgb_model, param_grid=param_grid, scoring='accuracy', cv=3, verbose=1, n_jobs=-1)
grid_search.fit(X_train, Y_train)

# Get the best model
best_xgb_model = grid_search.best_estimator_
print("Best parameters found: ", grid_search.best_params_)

# Make predictions with the best model
predictions = best_xgb_model.predict(X_test)

# Calculate evaluation metrics
accuracy = accuracy_score(Y_test, predictions)
precision = precision_score(Y_test, predictions)
recall = recall_score(Y_test, predictions)
f1 = f1_score(Y_test, predictions)
conf_matrix = confusion_matrix(Y_test, predictions)

# Print evaluation metrics
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")
print(f"Confusion Matrix: \n{conf_matrix}")

/home/innobridge/anaconda3/bin/python
Fitting 3 folds for each of 1 candidates, totalling 3 fits
Best parameters found:  {'colsample_bylevel': 1, 'colsample_bynode': 1, 'colsample_bytree': 0.8, 'gamma': 0.2, 'learning_rate': 0.2, 'max_depth': 6, 'min_child_weight': 3, 'n_estimators': 182, 'reg_alpha': 10, 'reg_lambda': 5, 'scale_pos_weight': 1, 'subsample': 0.75}
Accuracy: 0.8144027541203848
Precision: 0.8306063522617901
Recall: 0.7887249419772238
F1 Score: 0.809124049321186
Confusion Matrix: 
[[70199 13376]
 [17569 65588]]


In [48]:
import sys
print(sys.executable)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import xgboost as xgb
import warnings

# Suppress specific warnings from xgboost
warnings.filterwarnings(action='ignore', category=UserWarning, message='.*gpu_id.*')
warnings.filterwarnings(action='ignore', category=UserWarning, message='.*gpu_hist.*')

# Load data
file_path = r"/home/innobridge/sherry/Final_Balanced_Data.csv"
data = pd.read_csv(file_path)

# Define poverty threshold and create target variable
poverty_threshold = 13590
data['poverty_status'] = np.where(data['PINCP'] <= poverty_threshold, 1, 0)

# Drop the PINCP column
data = data.drop(columns=['PINCP'])

# Split data into features and target
X = data.drop(columns=['poverty_status'])
Y = data['poverty_status']

# Split data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=18)

# Define parameter grid for GridSearchCV
param_grid = {
    'n_estimators': [182],             
    'max_depth': [6],   
}

# Initialize XGBoost classifier without use_label_encoder, using GPU
xgb_model = xgb.XGBClassifier(random_state=18, eval_metric='logloss')

# Perform grid search
grid_search = GridSearchCV(estimator=xgb_model, param_grid=param_grid, scoring='accuracy', cv=3, verbose=1, n_jobs=-1)
grid_search.fit(X_train, Y_train)

# Get the best model
best_xgb_model = grid_search.best_estimator_
print("Best parameters found: ", grid_search.best_params_)

# Make predictions with the best model
predictions = best_xgb_model.predict(X_test)

# Calculate evaluation metrics
accuracy = accuracy_score(Y_test, predictions)
precision = precision_score(Y_test, predictions)
recall = recall_score(Y_test, predictions)
f1 = f1_score(Y_test, predictions)
conf_matrix = confusion_matrix(Y_test, predictions)

# Print evaluation metrics
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")
print(f"Confusion Matrix: \n{conf_matrix}")

/home/innobridge/anaconda3/bin/python
Fitting 3 folds for each of 1 candidates, totalling 3 fits
Best parameters found:  {'max_depth': 6, 'n_estimators': 182}
Accuracy: 0.8148225895448984
Precision: 0.8306392451493765
Recall: 0.7897350794280698
F1 Score: 0.8096708770242697
Confusion Matrix: 
[[70185 13390]
 [17485 65672]]


In [60]:
import sys
print(sys.executable)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import xgboost as xgb
import warnings

# Suppress specific warnings from xgboost
warnings.filterwarnings(action='ignore', category=UserWarning, message='.*gpu_id.*')
warnings.filterwarnings(action='ignore', category=UserWarning, message='.*gpu_hist.*')

# Load data
file_path = r"/home/innobridge/sherry/Final_Balanced_Data.csv"
data = pd.read_csv(file_path)

# Define poverty threshold and create target variable
poverty_threshold = 13590
data['poverty_status'] = np.where(data['PINCP'] <= poverty_threshold, 1, 0)

# Drop the PINCP column
data = data.drop(columns=['PINCP'])

# Split data into features and target
X = data.drop(columns=['poverty_status'])
Y = data['poverty_status']

# Split data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=18)

# Define parameter grid for GridSearchCV
param_grid = {
    'n_estimators': [182, 200],             
    'max_depth': [5, 6, 7],   
    'learning_rate': [0.1, 0.2, 0.3],   
    'min_child_weight': [2.5, 3, 4],
}

# Initialize XGBoost classifier without use_label_encoder, using GPU
xgb_model = xgb.XGBClassifier(random_state=18, eval_metric='logloss')

# Perform grid search
grid_search = GridSearchCV(estimator=xgb_model, param_grid=param_grid, scoring='accuracy', cv=3, verbose=1, n_jobs=-1)
grid_search.fit(X_train, Y_train)

# Get the best model
best_xgb_model = grid_search.best_estimator_
print("Best parameters found: ", grid_search.best_params_)

# Make predictions with the best model
predictions = best_xgb_model.predict(X_test)

# Calculate evaluation metrics
accuracy = accuracy_score(Y_test, predictions)
precision = precision_score(Y_test, predictions)
recall = recall_score(Y_test, predictions)
f1 = f1_score(Y_test, predictions)
conf_matrix = confusion_matrix(Y_test, predictions)

# Print evaluation metrics
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")
print(f"Confusion Matrix: \n{conf_matrix}")

/home/innobridge/anaconda3/bin/python
Fitting 3 folds for each of 54 candidates, totalling 162 fits
Best parameters found:  {'learning_rate': 0.2, 'max_depth': 7, 'min_child_weight': 3, 'n_estimators': 182}
Accuracy: 0.8149425425233309
Precision: 0.8301977322659663
Recall: 0.7906730642038553
F1 Score: 0.809953496966524
Confusion Matrix: 
[[70127 13448]
 [17407 65750]]


In [81]:
import sys
print(sys.executable)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import xgboost as xgb
import warnings

# Suppress specific warnings from xgboost
warnings.filterwarnings(action='ignore', category=UserWarning, message='.*gpu_id.*')
warnings.filterwarnings(action='ignore', category=UserWarning, message='.*gpu_hist.*')

# Load data
file_path = r"/home/innobridge/sherry/Final_Balanced_Data.csv"
data = pd.read_csv(file_path)

# Define poverty threshold and create target variable
poverty_threshold = 13590
data['poverty_status'] = np.where(data['PINCP'] <= poverty_threshold, 1, 0)

# Drop the PINCP column
data = data.drop(columns=['PINCP'])

# Split data into features and target
X = data.drop(columns=['poverty_status'])
Y = data['poverty_status']

# Split data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=18)

# Define parameter grid for GridSearchCV
param_grid = {
    'n_estimators': [182],             
    'max_depth': [7],   
    'learning_rate': [0.2],   
    'min_child_weight': [3],
  'gamma': [0], 
    'subsample': [1.0],
    'colsample_bytree': [0.6],
    'colsample_bylevel': [1.0],
    'colsample_bynode': [1.0],
   'reg_alpha': [10],
    'reg_lambda': [1],
    'max_delta_step': [0],
    'scale_pos_weight': [1]
}

# Initialize XGBoost classifier without use_label_encoder, using GPU
xgb_model = xgb.XGBClassifier(random_state=18, eval_metric='logloss')

# Perform grid search
grid_search = GridSearchCV(estimator=xgb_model, param_grid=param_grid, scoring='accuracy', cv=3, verbose=1, n_jobs=-1)
grid_search.fit(X_train, Y_train)

# Get the best model
best_xgb_model = grid_search.best_estimator_
print("Best parameters found: ", grid_search.best_params_)

# Make predictions with the best model
predictions = best_xgb_model.predict(X_test)

# Calculate evaluation metrics
accuracy = accuracy_score(Y_test, predictions)
precision = precision_score(Y_test, predictions)
recall = recall_score(Y_test, predictions)
f1 = f1_score(Y_test, predictions)
conf_matrix = confusion_matrix(Y_test, predictions)

# Print evaluation metrics
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")
print(f"Confusion Matrix: \n{conf_matrix}")

/home/innobridge/anaconda3/bin/python
Fitting 3 folds for each of 3 candidates, totalling 9 fits
Best parameters found:  {'colsample_bylevel': 1.0, 'colsample_bynode': 1.0, 'colsample_bytree': 0.6, 'gamma': 0, 'learning_rate': 0.2, 'max_delta_step': 0, 'max_depth': 7, 'min_child_weight': 3, 'n_estimators': 182, 'reg_alpha': 10, 'reg_lambda': 1, 'scale_pos_weight': 1, 'subsample': 1.0}
Accuracy: 0.8153203944053931
Precision: 0.8310510943367598
Recall: 0.7903964789494571
F1 Score: 0.8102141193003217
Confusion Matrix: 
[[70213 13362]
 [17430 65727]]


In [90]:
import sys
print(sys.executable)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import xgboost as xgb
import warnings

# Suppress specific warnings from xgboost
warnings.filterwarnings(action='ignore', category=UserWarning, message='.*gpu_id.*')
warnings.filterwarnings(action='ignore', category=UserWarning, message='.*gpu_hist.*')

# Load data
file_path = r"/home/innobridge/sherry/Final_Balanced_Data.csv"
data = pd.read_csv(file_path)

# Define poverty threshold and create target variable
poverty_threshold = 13590
data['poverty_status'] = np.where(data['PINCP'] <= poverty_threshold, 1, 0)

# Drop the PINCP column
data = data.drop(columns=['PINCP'])

# Split data into features and target
X = data.drop(columns=['poverty_status'])
Y = data['poverty_status']

# Split data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=18)

# Define parameter grid for GridSearchCV
param_grid = {
    'n_estimators': [100, 200, 500, 800],             
    'max_depth': [7, 8, 9],   
    'learning_rate': [0.1, 0.2],   
    'min_child_weight': [2, 3],
  'gamma': [0], 
    'subsample': [1.0],
    'colsample_bytree': [0.6],
    'colsample_bylevel': [1.0],
    'colsample_bynode': [1.0],
   'reg_alpha': [10],
    'reg_lambda': [1],
    'max_delta_step': [0],
    'scale_pos_weight': [1]
}

# Initialize XGBoost classifier without use_label_encoder, using GPU
xgb_model = xgb.XGBClassifier(random_state=18, eval_metric='logloss')

# Perform grid search
grid_search = GridSearchCV(estimator=xgb_model, param_grid=param_grid, scoring='accuracy', cv=3, verbose=1, n_jobs=-1)
grid_search.fit(X_train, Y_train)

# Get the best model
best_xgb_model = grid_search.best_estimator_
print("Best parameters found: ", grid_search.best_params_)

# Make predictions with the best model
predictions = best_xgb_model.predict(X_test)

# Calculate evaluation metrics
accuracy = accuracy_score(Y_test, predictions)
precision = precision_score(Y_test, predictions)
recall = recall_score(Y_test, predictions)
f1 = f1_score(Y_test, predictions)
conf_matrix = confusion_matrix(Y_test, predictions)

# Print evaluation metrics
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")
print(f"Confusion Matrix: \n{conf_matrix}")

/home/innobridge/anaconda3/bin/python
Fitting 3 folds for each of 48 candidates, totalling 144 fits
Best parameters found:  {'colsample_bylevel': 1.0, 'colsample_bynode': 1.0, 'colsample_bytree': 0.6, 'gamma': 0, 'learning_rate': 0.1, 'max_delta_step': 0, 'max_depth': 8, 'min_child_weight': 2, 'n_estimators': 500, 'reg_alpha': 10, 'reg_lambda': 1, 'scale_pos_weight': 1, 'subsample': 1.0}
Accuracy: 0.8158421898615743
Precision: 0.830718789407314
Recall: 0.7921882703801243
F1 Score: 0.810996140517183
Confusion Matrix: 
[[70151 13424]
 [17281 65876]]


In [91]:
import sys
print(sys.executable)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import xgboost as xgb
import warnings

# Suppress specific warnings from xgboost
warnings.filterwarnings(action='ignore', category=UserWarning, message='.*gpu_id.*')
warnings.filterwarnings(action='ignore', category=UserWarning, message='.*gpu_hist.*')

# Load data
file_path = r"/home/innobridge/sherry/Final_Balanced_Data.csv"
data = pd.read_csv(file_path)

# Define poverty threshold and create target variable
poverty_threshold = 13590
data['poverty_status'] = np.where(data['PINCP'] <= poverty_threshold, 1, 0)

# Drop the PINCP column
data = data.drop(columns=['PINCP'])

# Split data into features and target
X = data.drop(columns=['poverty_status'])
Y = data['poverty_status']

# Split data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=18)

# Define parameter grid for GridSearchCV
param_grid = {
    'n_estimators': [500],             
    'max_depth': [8],   
    'learning_rate': [0.05, 0.1],   
    'min_child_weight': [1],
  'gamma': [0], 
    'subsample': [1.0],
    'colsample_bytree': [1, 0.6, 0.4],
    'colsample_bylevel': [1.0],
    'colsample_bynode': [1.0],
   'reg_alpha': [10],
    'reg_lambda': [1],
    'max_delta_step': [0],
    'scale_pos_weight': [1]
}

# Initialize XGBoost classifier without use_label_encoder, using GPU
xgb_model = xgb.XGBClassifier(random_state=18, eval_metric='logloss')

# Perform grid search
grid_search = GridSearchCV(estimator=xgb_model, param_grid=param_grid, scoring='accuracy', cv=3, verbose=1, n_jobs=-1)
grid_search.fit(X_train, Y_train)

# Get the best model
best_xgb_model = grid_search.best_estimator_
print("Best parameters found: ", grid_search.best_params_)

# Make predictions with the best model
predictions = best_xgb_model.predict(X_test)

# Calculate evaluation metrics
accuracy = accuracy_score(Y_test, predictions)
precision = precision_score(Y_test, predictions)
recall = recall_score(Y_test, predictions)
f1 = f1_score(Y_test, predictions)
conf_matrix = confusion_matrix(Y_test, predictions)

# Print evaluation metrics
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")
print(f"Confusion Matrix: \n{conf_matrix}")

/home/innobridge/anaconda3/bin/python
Fitting 3 folds for each of 162 candidates, totalling 486 fits


/home/innobridge/anaconda3/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(


Best parameters found:  {'colsample_bylevel': 1.0, 'colsample_bynode': 1.0, 'colsample_bytree': 0.6, 'gamma': 0, 'learning_rate': 0.1, 'max_delta_step': 0, 'max_depth': 8, 'min_child_weight': 1, 'n_estimators': 500, 'reg_alpha': 10, 'reg_lambda': 1, 'scale_pos_weight': 1, 'subsample': 1.0}
Accuracy: 0.8157522251277499
Precision: 0.8304616897112391
Recall: 0.7923325757302452
F1 Score: 0.81094919259551
Confusion Matrix: 
[[70124 13451]
 [17269 65888]]
